name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies (if needed)
      run: |
        # 如果有package.json，安装依赖
        if [ -f package.json ]; then
          npm ci
        fi
        
    - name: Build (if needed)
      run: |
        # 如果有构建脚本，执行构建
        if [ -f package.json ] && npm run build --if-present; then
          echo "Build completed"
        else
          echo "No build step needed for static site"
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,README.md'
